name: Glitch Sync

on:
  push:
    branches:
      - main

jobs:
  # Read: https://support.glitch.com/t/automating-deployment-from-github-how-to/
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Glitch Project
        uses: wei/git-sync@v3
        with:
          source_repo: https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          source_branch: main
          destination_repo: ${{ secrets.GLITCH_GIT_URL }}
          destination_branch: main
